Bump safe_yaml gem to 1.0.4 so that gh-pages can be generated with ruby 2.2.x
When running the `jekyll` command with ruby 2.2.x, an exception is
raised from within the safe_yaml gem:

```
/Users/ryan/.rvm/gems/ruby-2.2.0-preview1/gems/safe_yaml-1.0.3/lib/safe_yaml/load.rb:43:in `<module:SafeYAML>': undefined method `tagged_classes' for Psych:Module (NoMethodError)
```

Upgrading the gem to version 1.0.4 fixes this issue and allows running
the `jekyll` command again using ruby 2.2.x.

See this[0] issue for the issue being tracked in safe_yaml.

[0] - https://github.com/dtao/safe_yaml/issues/73